data = [
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_000/decomp_bag_000",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_000/dry_wt_000",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_001/decomp_bag_001",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_001/dry_wt_001",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_002/decomp_bag_002",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_002/dry_wt_002",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_003/decomp_bag_003",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_003/dry_wt_003",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_004/decomp_bag_004",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_004/dry_wt_004",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_005/decomp_bag_005",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_005/dry_wt_005",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_006/decomp_bag_006",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_006/dry_wt_006",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_007/decomp_bag_007",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_007/dry_wt_007",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_008/decomp_bag_008",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_008/dry_wt_008",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_009/decomp_bag_009",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_009/dry_wt_009",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_010/decomp_bag_010",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_010/dry_wt_010",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_011/decomp_bag_011",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_011/dry_wt_011",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_012/decomp_bag_012",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_012/dry_wt_012",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_013/decomp_bag_013",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_013/dry_wt_013",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_014/decomp_bag_014",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_014/dry_wt_014",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_015/decomp_bag_015",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_015/dry_wt_015",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_016/decomp_bag_016",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_016/dry_wt_016",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_017/decomp_bag_017",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_017/dry_wt_017",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_018/decomp_bag_018",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_018/dry_wt_018",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_019/decomp_bag_019",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_019/dry_wt_019",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_020/decomp_bag_020",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_020/dry_wt_020",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_021/decomp_bag_021",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_021/dry_wt_021",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_022/decomp_bag_022",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_022/dry_wt_022",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
    {
        "cols_from_form": [
            {
                "kobo_name": "dry_wt_group_023/decomp_bag_023",
                "db_names": ["code", "subplot", "subsample", "time"],
                "separator": "-",
                "indices": [0,1,2,3],
                "tests": ["check_reqex ^[A-Z0-9]{3}-[12]-[AB]-[0-5]$"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "dry_wt_group_023/dry_wt_023",
                "db_names": ["empty_bag_wt"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "WON'T BE FOUND",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
        ],
        "extra_cols": None
    },
]