data = [
    {
        "cols_from_form": [
            {
                "kobo_name": "What_is_your_Farm_Code",
                "db_names": ["code"],
                "separator": None,
                "indices": None,
                "tests": ["not_null", "check_reqex [A-Z]{3}"],
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "In_which_subplot_are_ur_sensors_installed",
                "db_names": ["subplot"],
                "separator": "_",
                "indices": [1],
                "tests": None,
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "Scan_the_barcode_on_side_of_your_Gateway",
                "db_names": ["gateway_serial_no"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "Scan_your_bare_node",
                "db_names": ["bare_node_serial_no"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "Scan_your_cover_crop_node",
                "db_names": ["cover_node_serial_no"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "code",
                "db_names": ["time_begin"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "code",
                "db_names": ["time_end"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": ["strip_whitespace", "to_uppercase"],
            },
            {
                "kobo_name": "Any_issues_to_report_about_your_sensors",
                "db_names": ["notes"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "_submitted_by",
                "db_names": ["submitted_by"],
                "separator": None,
                "indices": None,
                "tests": None,
                "conversions": [],
            },
            {
                "kobo_name": "What_is_the_GPS_loca_on_of_your_bare_node",
                "db_names": ["bare_lon_REAL", "bare_lat_REAL"],
                "separator": " ",
                "indices": [0,1],
                "tests": ["not_null"],
                "conversions": [],         
            },
            {
                "kobo_name": "What_is_the_GPS_loca_your_cover_crop_node",
                "db_names": ["cover_lon_REAL", "cover_lat_REAL"],
                "separator": " ",
                "indices": [0,1],
                "tests": ["not_null"],
                "conversions": [],         
            },
        ],
        "extra_cols": None
    }
]